// Roles
const roleData = [
  // /*** @AdminSetting */
  {
    name: 'admin-setting',
    module: 'Setting',
    title: 'Admin Setting',
    index: 10,
  },
  {
    name: 'exchange',
    module: 'Setting',
    title: 'Admin Setting',
    index: 10,
  },
  {
    name: 'group-user',
    module: 'Setting',
    title: 'Admin Setting',
    index: 10,
  },
  {
    name: 'user',
    module: 'Setting',
    title: 'Admin Setting',
    index: 10,
  },
  {
    name: 'employee',
    module: 'Setting',
    title: 'Admin Setting',
    index: 10,
  },
  {
    name: 'location',
    module: 'Setting',
    title: 'Admin Setting',
    index: 10,
  },
  {
    name: 'closing-date',
    module: 'Setting',
    title: 'Admin Setting',
    index: 10,
  },
  {
    name: 'closing-report',
    module: 'Setting',
    title: 'Admin Setting',
    index: 10,
  },
  {
    name: 'user-mapping',
    module: 'Setting',
    title: 'Admin Setting',
    index: 10,
  },
  //{
  //  name: 'chart-acc',
  //  moduleRole: 'journal',
  //  module: 'Setting',
  //  title: 'Dashboard',
  //  index: 10,
  //},
  //{
  //  name: 'account-info',
  //  moduleRole: 'journal',
  //  module: 'Setting',
  //  title: 'Dashboard',
  //  index: 10,
  //},
  //{
  //  name: 'account-setting',
  //  moduleRole: 'journal',
  //  module: 'Setting',
  //  title: 'Account Setting',
  //  index: 10,
  //},
  //  /*** @Accounting */
  //  {
  //    name: 'audit-log',
  //    module: 'Account',
  //    moduleRole: 'journal',
  //    title: 'Account Form',
  //    index: 9,
  //  },
  //  {
  //    name: 'journal-insert',
  //    moduleRole: 'journal',
  //    module: 'Account',
  //    title: 'Account Form',
  //    index: 9,
  //  },
  //  {
  //    name: 'journal-update',
  //    moduleRole: 'journal',
  //    module: 'Account',
  //    title: 'Account Form',
  //    index: 9,
  //  },
  //  {
  //    name: 'journal-remove',
  //    moduleRole: 'journal',
  //    module: 'Account',
  //    title: 'Account Form',
  //    index: 9,
  //  },
  //  {
  //    name: 'cash-transaction-insert',
  //    module: 'Account',
  //    moduleRole: 'cash-transaction',
  //    title: 'Account Form',
  //    index: 9,
  //  },
  //  {
  //    name: 'cash-transaction-update',
  //    module: 'Account',
  //    moduleRole: 'cash-transaction',
  //    title: 'Account Form',
  //    index: 9,
  //  },
  //  {
  //    name: 'cash-transaction-remove',
  //    module: 'Account',
  //    moduleRole: 'cash-transaction',
  //    title: 'Account Form',
  //    index: 9,
  //  },
  //  {
  //    name: 'cash-revenue-insert',
  //    module: 'Account',
  //    moduleRole: 'cash-revenue',
  //    title: 'Account Form',
  //    index: 9,
  //  },
  //  {
  //    name: 'cash-revenue-update',
  //    module: 'Account',
  //    moduleRole: 'cash-revenue',
  //    title: 'Account Form',
  //    index: 9,
  //  },
  //  {
  //    name: 'cash-revenue-remove',
  //    module: 'Account',
  //    moduleRole: 'cash-revenue',
  //    title: 'Account Form',
  //    index: 9,
  //  },
  //  {
  //    name: 'cash-expense-insert',
  //    module: 'Account',
  //    moduleRole: 'cash-expense',
  //    title: 'Account Form',
  //    index: 9,
  //  },
  //  {
  //    name: 'cash-expense-update',
  //    module: 'Account',
  //    moduleRole: 'cash-expense',
  //    title: 'Account Form',
  //    index: 9,
  //  },
  //  {
  //    name: 'cash-expense-remove',
  //    module: 'Account',
  //    moduleRole: 'cash-expense',
  //    title: 'Account Form',
  //    index: 9,
  //  },
  //  {
  //    name: 'closing-report-remove',
  //    moduleRole: 'journal',
  //    module: 'Account',
  //    title: 'Account Form',
  //    index: 9,
  //  },
  //  {
  //    name: 'chart-of-account-insert',
  //    moduleRole: 'journal',
  //    module: 'Account',
  //    title: 'Account Form',
  //    index: 9,
  //  },
  //  {
  //    name: 'chart-of-account-update',
  //    moduleRole: 'journal',
  //    module: 'Account',
  //    title: 'Account Form',
  //    index: 9,
  //  },
  //  {
  //    name: 'chart-of-account-remove',
  //    moduleRole: 'journal',
  //    module: 'Account',
  //    title: 'Account Form',
  //    index: 9,
  //  },
  //  // Report
  //  {
  //    name: 'journal-report',
  //    moduleRole: 'journal-report',
  //    module: 'Account',
  //    title: 'Account Report',
  //    index: 10,
  //  },
  //  {
  //    name: 'ledger-report',
  //    moduleRole: 'ledger-report',
  //    module: 'Account',
  //    title: 'Account Report',
  //    index: 10,
  //  },
  //  {
  //    name: 'trial-balance-report',
  //    moduleRole: 'trial-balance-report',
  //    module: 'Account',
  //    title: 'Account Report',
  //    index: 10,
  //  },
  //  {
  //    name: 'profit-loss-report',
  //    moduleRole: 'profit-loss-report',
  //    module: 'Account',
  //    title: 'Account Report',
  //    index: 10,
  //  },
  //  {
  //    name: 'profit-loss-comparison-report',
  //    moduleRole: 'profit-loss-comparison-report',
  //    module: 'Account',
  //    title: 'Account Report',
  //    index: 10,
  //  },
  //  {
  //    name: 'profit-loss-by-month-report',
  //    moduleRole: 'profit-loss-by-month-report',
  //    module: 'Account',
  //    title: 'Account Report',
  //    index: 10,
  //  },
  //  {
  //    name: 'profit-loss-by-class-report',
  //    moduleRole: 'profit-loss-by-class-report',
  //    module: 'Account',
  //    title: 'Account Report',
  //    index: 10,
  //  },
  //  {
  //    name: 'balance-sheet-report',
  //    moduleRole: 'balance-sheet-report',
  //    module: 'Account',
  //    title: 'Account Report',
  //    index: 10,
  //  },
  //  {
  //    name: 'balance-sheet-comparison-report',
  //    moduleRole: 'balance-sheet-comparison-report',
  //    module: 'Account',
  //    title: 'Account Report',
  //    index: 10,
  //  },
  //  {
  //    name: 'cash-report',
  //    moduleRole: 'cash-report',
  //    module: 'Account',
  //    title: 'Account Report',
  //    index: 10,
  //  },
  //  {
  //    name: 'transaction-detail-report',
  //    moduleRole: 'transaction-detail-report',
  //    module: 'Account',
  //    title: 'Account Report',
  //    index: 10,
  //  },
  //  {
  //    name: 'account-list-report',
  //    moduleRole: 'account-list-report',
  //    module: 'Account',
  //    title: 'Account Report',
  //    index: 10,
  //  },
  //  // Authorize level
  //  // FIXED ASSET
  //  {
  //    name: 'fixed-asset-setting',
  //    moduleRole: 'fixed-asset',
  //    module: 'Setting',
  //    title: 'Account Setting',
  //    index: 10,
  //  },
  //  {
  //    name: 'fixed-asset-type-insert',
  //    moduleRole: 'fixed-asset',
  //    module: 'Account',
  //    title: 'Fixed Asset',
  //    index: 9,
  //  },
  //  {
  //    name: 'fixed-asset-type-update',
  //    moduleRole: 'fixed-asset',
  //    module: 'Account',
  //    title: 'Fixed Asset',
  //    index: 9,
  //  },
  //  {
  //    name: 'fixed-asset-type-remove',
  //    moduleRole: 'fixed-asset',
  //    module: 'Account',
  //    title: 'Fixed Asset',
  //    index: 9,
  //  },
  //  {
  //    name: 'fixed-asset-insert',
  //    moduleRole: 'fixed-asset',
  //    module: 'Account',
  //    title: 'Fixed Asset',
  //    index: 9,
  //  },
  //  {
  //    name: 'fixed-asset-update',
  //    moduleRole: 'fixed-asset',
  //    module: 'Account',
  //    title: 'Fixed Asset',
  //    index: 9,
  //  },
  //  {
  //    name: 'fixed-asset-remove',
  //    moduleRole: 'fixed-asset',
  //    module: 'Account',
  //    title: 'Fixed Asset',
  //    index: 9,
  //  },
  //  {
  //    name: 'sale-fixed-asset-insert',
  //    moduleRole: 'fixed-asset',
  //    module: 'Account',
  //    title: 'Fixed Asset',
  //    index: 9,
  //  },
  //  {
  //    name: 'disposal-fixed-asset-insert',
  //    moduleRole: 'fixed-asset',
  //    module: 'Account',
  //    title: 'Fixed Asset',
  //    index: 9,
  //  },
  //  {
  //    name: 'sale-fixed-asset-remove',
  //    moduleRole: 'fixed-asset',
  //    module: 'Account',
  //    title: 'Fixed Asset',
  //    index: 9,
  //  },
  //  {
  //    name: 'disposal-fixed-asset-remove',
  //    moduleRole: 'fixed-asset',
  //    module: 'Account',
  //    title: 'Fixed Asset',
  //    index: 9,
  //  },
  //  {
  //    name: 'depreciation-fixed-asset-insert',
  //    moduleRole: 'fixed-asset',
  //    module: 'Account',
  //    title: 'Fixed Asset',
  //    index: 9,
  //  },
  //  {
  //    name: 'depreciation-fixed-asset-remove',
  //    moduleRole: 'fixed-asset',
  //    module: 'Account',
  //    title: 'Fixed Asset',
  //    index: 9,
  //  },
  //  {
  //    name: 'transfer-fixed-asset-insert',
  //    moduleRole: 'fixed-asset',
  //    module: 'Account',
  //    title: 'Fixed Asset',
  //    index: 9,
  //  },
  //  {
  //    name: 'transfer-fixed-asset-update',
  //    moduleRole: 'fixed-asset',
  //    module: 'Account',
  //    title: 'Fixed Asset',
  //    index: 9,
  //  },
  //  {
  //    name: 'transfer-fixed-asset-remove',
  //    moduleRole: 'fixed-asset',
  //    module: 'Account',
  //    title: 'Fixed Asset',
  //    index: 9,
  //  },
  //  // END FIXED ASSET
]

export default roleData
